### PR TITLE
Add basic macOS compilation functionality

### PR DESCRIPTION
**Pull request by droark**
- Allow compilation on macOS while not interfering with *NIX compilation.

### CODE REVIEW

**Comment by droark** [comment]
Caveat: I haven't tested the Linux build yet. macOS build is fine. I'll spin this up in Docker in a bit and make sure everything's hunky dory.

**Comment by nexus166** [comment]
lol wut? Why'd you run this in macOS anyway

**Comment by droark** [comment]
Sorry. That was unintentional. Some wires got crossed.

As for running it in macOS, why not? :)

**Comment by nexus166** [comment]
Well, my use case for this was plugging in a SoftHSM installation (to be replaced with a real appliance eventually)..security wise I wouldn't consider macOS an appropriate env for production

**Comment by droark** [comment]
That assumes one wishes to use this in production. One may have other reasons for wanting to use this. Students, for example.

In any event, as mentioned earlier, this was unintentional. Please disregard. Thanks.

**Pull request closed without merging**
